2020-07-22 12:18:47,437 ERROR 15048 nodejs.ClusterClientNoResponseError: client no response in 992894ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\28067\Desktop\shopping\server\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 15048
hostname: LAPTOP-Q8E1FL5T

2020-07-22 13:29:16,303 ERROR 15048 nodejs.ClusterClientNoResponseError: client no response in 1747962ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\28067\Desktop\shopping\server\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 15048
hostname: LAPTOP-Q8E1FL5T

2020-07-22 22:46:27,303 ERROR 7464 nodejs.ClusterClientNoResponseError: client no response in 4270693ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\28067\Desktop\shopping\server\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 7464
hostname: LAPTOP-Q8E1FL5T

2020-07-22 23:03:28,359 ERROR 7464 nodejs.ClusterClientNoResponseError: client no response in 160977ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\28067\Desktop\shopping\server\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 7464
hostname: LAPTOP-Q8E1FL5T

2020-07-23 12:52:33,470 ERROR 13808 nodejs.ClusterClientNoResponseError: client no response in 3053120ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\28067\Desktop\shopping\server\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13808
hostname: LAPTOP-Q8E1FL5T

2020-07-23 13:31:09,323 ERROR 13808 nodejs.ClusterClientNoResponseError: client no response in 694934ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\28067\Desktop\shopping\server\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13808
hostname: LAPTOP-Q8E1FL5T

2020-07-24 13:30:56,319 ERROR 4352 nodejs.ClusterClientNoResponseError: client no response in 5312451ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\28067\Desktop\shopping\server\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4352
hostname: LAPTOP-Q8E1FL5T

2020-07-24 20:39:41,459 ERROR 15588 nodejs.ClusterClientNoResponseError: client no response in 4971006ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\28067\Desktop\shopping\server\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 15588
hostname: LAPTOP-Q8E1FL5T

2020-07-24 21:52:51,704 ERROR 15588 nodejs.ClusterClientNoResponseError: client no response in 2637521ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\28067\Desktop\shopping\server\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 15588
hostname: LAPTOP-Q8E1FL5T

2020-07-24 22:47:51,911 ERROR 15588 nodejs.ClusterClientNoResponseError: client no response in 399698ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\28067\Desktop\shopping\server\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 15588
hostname: LAPTOP-Q8E1FL5T

